version: '3'
services:
  api:
    container_name: back
    restart: always
    build:
      context: ./back
    ports:
      - "5000:5000"
  app:
    container_name: front
    restart: always
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
