version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pge
      MYSQL_USER: pge
      MYSQL_PASSWORD: pge
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
